name: domain
description: Domain layer
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0
  get_it: ^7.2.0
  injectable: ^1.5.3

dev_dependencies:
  build_runner: ^2.1.7
  injectable_generator: ^1.5.3